# Assignment 3

In [1]:
# Create a numpy array starting with step size of 3

In [2]:
import numpy as np

In [3]:
array1 = np.arange(2,50,3)

In [4]:
print(array1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [5]:
print(type(array1))

<class 'numpy.ndarray'>


In [6]:
# Problem 2
import numpy as np

In [7]:
# creating empty list1
list1 = list()
n1 = int(input('Enter the number of elements:'))
for i in range(0,n1):
    element = int(input())
    list1.append(element)
    
print(list1)

Enter the number of elements:5
1
2
3
45
95
[1, 2, 3, 45, 95]


In [8]:
# creating empty list 2

In [9]:
list2 = list()
n2 = int(input('Enter the number of elements'))
for i in range(0,n2):
    element = int(input())
    list2.append(element)
    
print(list2)


Enter the number of elements5
56
32
123
89
741
[56, 32, 123, 89, 741]


In [10]:
# coverting these lists into numpy arrays

array1 = np.array(list1)
array2 = np.array(list2)
print(array1)
print(array2)
print(type(array1))
print(type(array2))

[ 1  2  3 45 95]
[ 56  32 123  89 741]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Concatnating these two arrays

In [11]:
Array = np.concatenate((array1,array2))

In [12]:
print(Array)
print(type(Array))

[  1   2   3  45  95  56  32 123  89 741]
<class 'numpy.ndarray'>


In [13]:
# Sorting Array
print(np.sort(Array))

[  1   2   3  32  45  56  89  95 123 741]


# Code Snippent of problem 3 to find size and dimension of ndarray

In [14]:
import numpy as np

In [15]:
a_1d = np.arange(3) # 1 d array
print(a_1d)

[0 1 2]


In [16]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
a_3d = np.arange(24).reshape((2,3,4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [18]:
# Number of dimensions of numpy.ndarray: ndim

In [19]:
print(a_1d.ndim)
# 1

print(type(a_1d.ndim))
# <class 'int'>

print(a_2d.ndim)
# 2

print(a_3d.ndim)

1
<class 'int'>
2
3


In [20]:
# Size of numpy.ndArray(total number of elements):size

In [21]:
print(a_1d.size)
# 3

print(type(a_1d.size))
# <class 'int'>

print(a_2d.size)
# 12

print(a_3d.size)
# 24


3
<class 'int'>
12
24


# Converting a 1d array into 2d array

In [22]:
# reshaping a 1d array to 2d array

In [23]:
import numpy as np

In [24]:
# Now reshaping 1d Array into 2d array using np.newaxis()
arr = np.arange(4)
#print(arr)
arr.shape


(4,)

In [25]:
# make it a row vector by inserting an axis along with first dimension
row_vec = arr[np.newaxis,:]
row_vec.shape
#print(row_vec)


(1, 4)

In [26]:
# make it as column vector by inserting an axis along second dimension
col_vec = arr[:,np.newaxis]
# print(col_vec)
print(col_vec.shape)

(4, 1)


In [27]:
# In this examplewe can see that using Numpy.expand_dims() method, we are able to get the expanded array using this method.
import numpy as np
new_array = np.array([1,2])
print(new_array.shape)
new_dimension_array = np.expand_dims(new_array, axis = 0)
print(new_dimension_array.shape)

(2,)
(1, 2)


# Stack two square numpy arrays vertically and horizontally

In [45]:
import numpy as np


In [46]:
Array_1 = np.array([[1,2],[3,4]])

In [47]:
print(Array_1)

[[1 2]
 [3 4]]


In [48]:
Array_2 = np.array([[5,6],[7,8]])
print(Array_2)

[[5 6]
 [7 8]]


In [49]:
# Stacking two arrays horizontally

In [50]:
out_Arr = np.hstack((Array_1,Array_2))
print(out_Arr)

[[1 2 5 6]
 [3 4 7 8]]


In [51]:
# Stacking two arrays vertically

In [52]:
out_arr = np.vstack((Array_1,Array_2))

In [53]:
print(out_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
# Finding unique items and counts of unique items

In [55]:
# Python’s numpy library provides a numpy.unique() function 
#to find the unique elements and it’s corresponding frequency in a numpy array.

In [56]:
import numpy as np

In [57]:
random_array = np.array([10,20,5,10,8,20,9])

In [58]:
# Get a tuple of unique values  
# and their frequency in 
# numpy array 

In [59]:
unique,frequency = np.unique(random_array,return_counts = True)

In [60]:
# print unique values array 
print("Unique Values:",  
      unique) 

Unique Values: [ 5  8  9 10 20]


In [61]:
# print frequency array 
print("Frequency Values:", 
      frequency)

Frequency Values: [1 1 1 2 2]


# Assignment 3 complete